### ISSUE TITLE
Unable to install the python package

### ISSUE THREAD

**Issue by mareq** [iduartgomez/rustypy#2]
```
$ uname
Darwin
$ python3 --version
Python 3.6.5
$ pip3 install rustypy
Collecting rustypy
  Using cached rustypy-0.1.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ql/4rlmpby133l94mq01ltbscrm0000gp/T/pip-build-5xlrabyn/rustypy/setup.py", line 21, in <module>
        long_description = '\n' + convert(f, 'rst')
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ql/4rlmpby133l94mq01ltbscrm0000gp/T/pip-build-5xlrabyn/rustypy/
```

**Comment by mareq** [comment]
Seems to be working when installed from source; current `master`: `971701a4e18aeffceda16f2538f3a846713e65ff`:
```
$ git clone git@github.com:iduartgomez/rustypy.git
Cloning into 'rustypy'...
remote: Counting objects: 1337, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1337 (delta 3), reused 17 (delta 3), pack-reused 1311
Receiving objects: 100% (1337/1337), 1.00 MiB | 0 bytes/s, done.
Resolving deltas: 100% (756/756), done.
$ cd rustypy/
$ pip3 install .
Processing /.../rustypy
    Complete output from command python setup.py egg_info:
    Maybe try:

        brew install pandoc
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ql/4rlmpby133l94mq01ltbscrm0000gp/T/pip-odh9hwiv-build/setup.py", line 21, in <module>
        long_description = '\n' + convert(f, 'rst')
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 69, in convert
        outputfile=outputfile, filters=filters)
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 260, in _convert_input
        _ensure_pandoc_path()
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 544, in _ensure_pandoc_path
        raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ql/4rlmpby133l94mq01ltbscrm0000gp/T/pip-odh9hwiv-build/
$ brew install pandoc
==> Downloading https://homebrew.bintray.com/bottles/pandoc-2.1.3.sierra.bottle.tar.gz
Already downloaded: /Users/mq/Library/Caches/Homebrew/pandoc-2.1.3.sierra.bottle.tar.gz
==> Pouring pandoc-2.1.3.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
�  /usr/local/Cellar/pandoc/2.1.3: 173 files, 65.2MB
$ pip3 install .
Processing /.../rustypy
Installing collected packages: rustypy
  Running setup.py install for rustypy ... done
Successfully installed rustypy-0.1.15
```

Installing `pandoc` using homebrew does not seem to help (it is installed at this point - see above):
```
$ pip3 uninstall rustypy
Uninstalling rustypy-0.1.15:
  /usr/local/bin/rustypy
  /usr/local/lib/python3.6/site-packages/rslib/__init__.py
  /usr/local/lib/python3.6/site-packages/rslib/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rslib/src/lib.rs
  /usr/local/lib/python3.6/site-packages/rslib/src/macros.rs
  /usr/local/lib/python3.6/site-packages/rslib/tests/macros.rs
  /usr/local/lib/python3.6/site-packages/rustypy-0.1.15-py3.6.egg-info
  /usr/local/lib/python3.6/site-packages/rustypy/__init__.py
  /usr/local/lib/python3.6/site-packages/rustypy/__main__.py
  /usr/local/lib/python3.6/site-packages/rustypy/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/__pycache__/__main__.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/__pycache__/pywrapper.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/__pycache__/scripts.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/pywrapper.py
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/__init__.py
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/__pycache__/__init__.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/__pycache__/ffi_defs.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/__pycache__/pytypes.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/__pycache__/rswrapper.cpython-36.pyc
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/ffi_defs.py
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/pytypes.py
  /usr/local/lib/python3.6/site-packages/rustypy/rswrapper/rswrapper.py
  /usr/local/lib/python3.6/site-packages/rustypy/scripts.py
Proceed (y/n)? y
  Successfully uninstalled rustypy-0.1.15
$ pip3 install rustypy
Collecting rustypy
  Using cached rustypy-0.1.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ql/4rlmpby133l94mq01ltbscrm0000gp/T/pip-build-iu4am90u/rustypy/setup.py", line 21, in <module>
        long_description = '\n' + convert(f, 'rst')
      File "/usr/local/lib/python3.6/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ql/4rlmpby133l94mq01ltbscrm0000gp/T/pip-build-iu4am90u/rustypy/
$ pip3 install .
Processing /.../rustypy
Installing collected packages: rustypy
  Running setup.py install for rustypy ... done
Successfully installed rustypy-0.1.15
```

**Comment by mareq** [comment]
I tried to follow the example in [wiki](https://github.com/iduartgomez/rustypy/wiki/Python-in-Rust), but it does not seem to work due to all kinds of problems... The [releases](https://github.com/iduartgomez/rustypy/releases) page claims that it is stable, though. Am I doing something wrong, is it supposed to work? Is there some full working example (in the form of code)?

**Comment by iduartgomez** [comment]
Thanks for opening the issue. I see you are using macOS, this library has been only tested against Linux, also Python 3.6.5 is not tested (Python 3.5 and 3.6.0 work and should be stable on those versions, but maybe there have been some breaking changes introduced in Python 3.6.5).

Also if you can execute the tests and report which ones are failing please, you can do by executing the following commands at the `rustypy` root directory.
```
$ python3 ./tests/test_py_to_rs.py
$ python3 ./tests/test_rs_to_py.py
```
If you try with Python 3.5 or 3.6.0 and it works let me know.

p.s: post the result of running `rustc --version` too just in case

**Comment by iduartgomez** [comment]
The pypandoc (install) problem probably is a result of a breaking change from using a newer/older version of pypandoc at first glance. Should be fixable by checking the version first and aborting in case that version is not covered.

The "problem" is that the pypandoc is used to autogenerate some documentation on updates, but is not related to the core functioning of the library,  so is not a requeriment (and not frozen at any version)  is just for convenience. I'll take a look at it asap. 

Fails in tests though are more problematic so reports on that are welcome.

EDIT: There seems two unrelated problems with pandoc, one is a problem of not finding some pandoc dependencies in the system (first one), second is cause some error running pandoc (when is already installed). Why it finally installs is something that escapes me right now, will have to look closer at it.

**Comment by Kelvinmantey1** [comment]
Hello! I use Mac OS and Python version 3.7.4 and I ran into the same issue -- "pip install rustypy" doesn't work for me. I tried "git clone git@github.com:iduartgomez/rustypy.git" but I don't have the access rights on the computer it requires. Is there any other way to install Rustypy? The error code I received when I ran "pip install rustypy
" can be found below:

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting rustypy
  Using cached https://files.pythonhosted.org/packages/ab/ac/ca1cdfc2e44b84af73ee364afd4fb6f6fe54a0c3a8dc426941831e139168/rustypy-0.1.15.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-vGbWjD/rustypy/setup.py", line 11, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-vGbWjD/rustypy/

**Comment by Kelvinmantey1** [comment]
Hello! 
I don't know if my previous comment was seen but I've been having trouble installing Rustypy on Python. The python version is 3.7.4 and I'm doing the work on a Mac OS. I've tried "**pip3 install rustypy --user**", which gave the result below:
'Collecting rustypy
  Using cached https://files.pythonhosted.org/packages/ab/ac/ca1cdfc2e44b84af73ee364afd4fb6f6fe54a0c3a8dc426941831e139168/rustypy-0.1.15.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-8p1vnjvy/rustypy/setup.py:21: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
      long_description = '\n' + convert(f, 'rst')
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-8p1vnjvy/rustypy/setup.py", line 21, in <module>
        long_description = '\n' + convert(f, 'rst')
      File "/Users/MANQ9R/Library/Python/3.7/lib/python/site-packages/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-8p1vnjvy/rustypy/'


 and "**pip install rustypy**" which gave the result below:
'DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting rustypy
  Using cached https://files.pythonhosted.org/packages/ab/ac/ca1cdfc2e44b84af73ee364afd4fb6f6fe54a0c3a8dc426941831e139168/rustypy-0.1.15.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-buGKp1/rustypy/setup.py", line 11, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_x/r6gv5dc97dd5d_lpf5klv2tr0000gr/T/pip-install-buGKp1/rustypy/' 

None worked. I also tried installing it from the source, as was suggested above but I didn't have the authorization to make due changes to the device I was using. Is there any other way to install Rustypy?

**Comment by iduartgomez** [comment]
Hello @Kelvinmantey1,

One of the errors you reported was due to trying installing with python2.7, but the error with python3.7 is the same that was reported a while ago.

It has been a long while since I've looked into this. Reading past comment seems there was some broken functionality on dependencies on MacOS while trying to generate documentation. Some dependencies upgrading is due (as well as Rust itself) so I may check that out and will try controlling any possible errors while trying to generate documentation (shouldn't ever be breaking for the library functioning).

> None worked. I also tried installing it from the source, as was suggested above but I didn't have the authorization to make due changes to the device I was using.

Are you trying to install with system wide python3 and that's maybe why you lack priviledges? Try to use a virtual env on your personal user space and see if that helps (I lack macOS development experience so this is my best guess).

**Comment by Kelvinmantey1** [comment]
Hello sir! Okay! I will try that! Thank you so much.

**Comment by iduartgomez** [comment]
@Kelvinmantey1 I just released a new version which is compatible with python3.7 (and 3.8) and should have fixed all the build problems with pandoc etc. if you still are interested and can try it out I would be thankful.

Thanks!

**Comment by iduartgomez** [comment]
This should be hopefully fixed already with last release.
